fix: emoji for Aircraft was deleted to evaluation, and Tower was changed from abstract to concrete class, and null Objects as parameters was verified

diff --git a/avaj/Makefile b/avaj/Makefile
--- a/avaj/Makefile
+++ b/avaj/Makefile
@@ -12,7 +12,8 @@ CLASSPATH = main/java
 BIN  = bin
 DOCS  = ../docs
 MAIN  = com.ft.pckg.simulator.Simulator
-SCENARIO = test/resources/scenario.txt
+#SCENARIO = test/resources/ko/scenario.txt
+SCENARIO := $(word 2, $(MAKECMDGOALS))
 
 # =====================
 # Find all source files
@@ -22,7 +23,7 @@ SOURCES := $(shell find $(CLASSPATH) -name "*.java")
 # =====================
 # Default target
 # =====================
-all: compile run
+all: compile
 
 # =====================
 # Compile sources
@@ -34,8 +35,16 @@ compile:
 # =====================
 # Run simulator
 # =====================
-run: compile
-	$(JAVA) -cp $(BIN) $(MAIN) $(SCENARIO)
+run: 
+#	$(JAVA) -cp $(BIN) $(MAIN) $(SCENARIO)
+ifndef SCENARIO
+	$(error Use: make run ok/scenario.txt)
+endif
+	@if [ ! -d "$(BIN)" ] || [ -z "$$(ls $(BIN) 2>/dev/null)" ]; then \
+		echo "Erro: bin/ required. Run 'make compile' first."; \
+		exit 1; \
+	fi
+	$(JAVA) -cp $(BIN) $(MAIN) test/resources/$(SCENARIO)
 
 # =====================
 # Docs constructor
@@ -44,11 +53,20 @@ docs:
 	mkdir -p $(DOCS)
 	$(JAVADOC) -d $(DOCS) -sourcepath main/java $(SOURCES)
 
-
 # =====================
 # Clean build artifacts
 # =====================
 clean:
-	rm -rf $(BIN) $(DOCS)
+	rm -rf $(BIN)
 
-.PHONY: all compile run docs clean
+# =====================
+# Clean docs files
+# =====================
+cdoc:
+	rm -rf $(DOCS)
+
+
+%:
+	@:
+
+.PHONY: all compile run docs clean cdoc
